{
  lib,
  config,
  pkgs,
  ...
}:
let
  cfg = config.custom.desktop.components.notifications.mako;
  inherit (lib) mkEnableOption mkIf;
  # Configuration parameters (Gruvbox Material Dark, medium contrast)
  colors = {
    background = "#282828"; # bg0
    text = "#d4be98"; # fg0
    border = "#7daea3"; # blue
    urgent = "#ea6962"; # red
  };
in
{
  options.custom.desktop.components.notifications.mako = {
    enable = mkEnableOption "Enable Mako Notification Daemon";
  };
  config = mkIf cfg.enable {
    environment.systemPackages = [ pkgs.mako ];
    systemd.user.services.mako = {
      description = "Mako Notification Daemon";
      wantedBy = [ "graphical-session.target" ];
      partOf = [ "graphical-session.target" ];
      after = [ "graphical-session.target" ];
      serviceConfig = {
        ExecStart = "${lib.getExe pkgs.mako}";
        Restart = "always";
        RestartSec = "1s";
      };
    };
    custom.hjem.cfg.files.".config/mako/config".text = ''
      # Mako Configuration
      # Generated by NixOS Module
      # General
      layer=overlay
      max-history=50
      sort=-time
      # Geometry
      anchor=top-right
      width=350
      height=150
      margin=20
      padding=15
      border-size=1
      border-radius=2
      # Style (Default)
      font=JetBrainsMono Nerd Font 10
      background-color=${colors.background}f0
      text-color=${colors.text}
      border-color=${colors.background}
      progress-color=over ${colors.border}
      # Icons
      icons=1
      max-icon-size=48
      icon-path=${pkgs.papirus-icon-theme}/share/icons/Papirus-Dark
      # Behavior
      default-timeout=5000
      ignore-timeout=0
      # Urgency: Critical
      [urgency=critical]
      border-color=${colors.urgent}
      default-timeout=0
    '';
  };
}
