{
  lib,
  config,
  pkgs,
  ...
}:
let
  cfg = config.custom.desktop.components.notifications.mako;
  inherit (lib) mkEnableOption mkIf;
  
  # Configuration parameters (Hardcoded theme for now, can be option-ized later)
  colors = {
    background = "#1e1e2e"; # Base
    text = "#cdd6f4";       # Text
    border = "#89b4fa";     # Blue
    urgent = "#f38ba8";     # Red
  };
in
{
  options.custom.desktop.components.notifications.mako = {
    enable = mkEnableOption "Enable Mako Notification Daemon";
  };

  config = mkIf cfg.enable {
    environment.systemPackages = [ pkgs.mako ];

    # 1. Systemd Service (Decoupled, Pure Systemd)
    systemd.user.services.mako = {
      description = "Mako Notification Daemon";
      wantedBy = [ "graphical-session.target" ];
      partOf = [ "graphical-session.target" ];
      after = [ "graphical-session.target" ];

      serviceConfig = {
        ExecStart = "${pkgs.mako}/bin/mako";
        Restart = "always";
        RestartSec = "1s";
      };
    };

    # 2. Configuration (via Hjem/Home Manager)
    # We define the config file content directly
    custom.hjem.cfg.files.".config/mako/config".text = ''
      # Mako Configuration
      # Generated by NixOS Module

      # General
      layer=overlay
      max-history=50
      sort=-time

      # Geometry
      anchor=top-right
      width=350
      height=150
      margin=20
      padding=15
      border-size=2
      border-radius=12

      # Style (Default)
      font=JetBrainsMono Nerd Font 10
      background-color=${colors.background}f0
      text-color=${colors.text}
      border-color=${colors.border}
      progress-color=over ${colors.border}

      # Icons
      icons=1
      max-icon-size=48
      icon-path=${pkgs.papirus-icon-theme}/share/icons/Papirus-Dark

      # Behavior
      default-timeout=5000
      ignore-timeout=0

      # Urgency: Critical
      [urgency=critical]
      border-color=${colors.urgent}
      default-timeout=0
    '';
  };
}
