
[main]
terminal=footclient -a '{cmd}' -T '{cmd}' {cmd}

font=monospace:size=11
dpi-aware=auto
icon-theme=Gruvbox-Plus-Dark
icons-enabled=yes

anchor=center
lines=8
width=50
horizontal-pad=24
vertical-pad=12
inner-pad=8

match-mode=fzf
show-actions=no
list-executables-in-path=no

layer=overlay
keyboard-focus=exclusive
exit-on-keyboard-focus-loss=yes

[colors]
# Gruvbox Material Dark - Medium Contrast
background=282828f2
text=d4be98ff
match=e78a4eff
selection=45403dff
selection-text=d4be98ff
selection-match=ea6962ff
border=7daea3ff
prompt=89b482ff
placeholder=7c6f64ff
input=d4be98ff
counter=928374ff
message=a89984ff

[border]
width=0
radius=6
